### ISSUE TITLE
Programowanie layoutu toolbara

### ISSUE THREAD

**Issue by wojkoks** [nifiz/MetodyLogistyczne#19]
Na podstawie figmy:
https://www.figma.com/design/rnWJGaxzhVqezMj0Ov6uRk/Main-Page?node-id=3-54&t=zBwo7zDqctmv2tbT-4

Na razie implementacja toolbara bez przycisków. Sam layout do którego będzie można wrzucić tabsy, przyciski itp

**Comment by wojkoks** [comment]
Tutaj brakuje jeszcze wydzielenia elementów toolbara tak jak na figmie. Chodzi o wydzielenie takich sekcji, imo wystarczy 4 obiekty Frame bo w nich chyba mozna zagniezdzac inne elementy a w rectangle chyba nue

**Comment by A-Janowski** [comment]
fixed
