### ISSUE TITLE
Projekt zakładki Mapa

### ISSUE THREAD

**Issue by wojkoks** [nifiz/MetodyLogistyczne#24]
Najlepiej zaprojektować tak aby nie odbiegał designowo od strony głównej. W razie co możemy przedyskutować co powinno się tam jeszcze znależć.

**Comment by olaf-kucharski** [comment]
Ogólnie to jest opcja żeby wrzucić tu API google maps
https://console.cloud.google.com/google/maps-apis/
można też spróbować dodać trackowanie przez współrzędne czy coś:
https://console.cloud.google.com/google/maps-apis/discover/reverse-geocoding
no i zmienić kolory żeby pasowało do aplikacji
console.cloud.google.com/google/maps-apis/discover/styled-map
